name: place_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_map: ^0.11.0
  geocoder: ^0.2.1
  google_fonts: ^2.0.0
  image_picker: ^0.7.2
  location: ^4.1.1
  provider: ^5.0.0
  sqflite: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
